### ISSUE TITLE
'DataArray' object has no attribute 'standard_name'

### ISSUE THREAD

**Issue by lewismc** [Reading-eScience-Centre/pycovjson#20]
I am running into the following issue when attempting to convert a particular data product (link below available in both netCDF3 and netCDF4) to covjson.
http://podaac-opendap.jpl.nasa.gov/opendap/allData/aquarius/L3/mapped/V4/7day_running/SCI/2015/158/Q20151582015164.L3m_R7_SCI_V4.0_SSS_1deg.bz2.html
If I use pycovjson to read the file all is well

```
lmcgibbn@LMC-056430 /usr/local/pycovjson(master) $ pycovjson-viewer -v ~/Desktop/Q20151582015164.L3m_R7_SCI_V4.0_SSS_1deg.bz2.nc4
<xarray.Dataset>
Dimensions:   (dim1: 3, dim2: 256, lat: 180, lon: 360)
Coordinates:
  * lat       (lat) float32 89.5 88.5 87.5 86.5 85.5 84.5 83.5 82.5 81.5 ...
  * lon       (lon) float32 -179.5 -178.5 -177.5 -176.5 -175.5 -174.5 -173.5 ...
  * dim1      (dim1) int64 0 1 2
  * dim2      (dim2) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
Data variables:
    l3m_data  (lat, lon) float64 nan nan nan nan nan nan nan nan nan nan nan ...
    palette   (dim1, dim2) int8 71 0 71 73 0 73 76 0 75 78 0 77 80 0 79 82 1 ...
Attributes:
    HDF5_GLOBAL.Product_Name: Q20151582015164.L3m_R7_SCI_V4.0_SSS_1deg
    HDF5_GLOBAL.Sensor_Name: Aquarius
    HDF5_GLOBAL.Sensor: Aquarius
    HDF5_GLOBAL.Title: Aquarius Level-3 Standard Mapped Image
    HDF5_GLOBAL.Data_Center: NASA/GSFC OBPG
    HDF5_GLOBAL.Mission: SAC-D Aquarius
    HDF5_GLOBAL.Mission_Characteristics: Nominal orbit: inclination=98.0 (Sun-synchronous); node=6PM (ascending); eccentricity=<0.002; altitude=657 km; ground speed=6.825 km/sec
    HDF5_GLOBAL.Sensor_Characteristics: Number of beams=3; channels per receiver=4; frequency 1.413 GHz; bits per sample=16; instatntaneous field of view=6.5 degrees; science data block period=1.44 sec
    HDF5_GLOBAL.Product_Type: R7
    HDF5_GLOBAL.Processing_Version: V4.0
    HDF5_GLOBAL.Software_Name: smigen
    HDF5_GLOBAL.Software_Version: 5.04
    HDF5_GLOBAL.Processing_Time: 2015184121146000
    HDF5_GLOBAL.Input_Files: Q20151582015164.L3b_R7_SCI_V4.0.main
    HDF5_GLOBAL.Processing_Control: smigen par=Q20151582015164.L3m_R7_SCI_V4.0_SSS_1deg.param
    HDF5_GLOBAL.Input_Parameters: ifile = Q20151582015164.L3b_R7_SCI_V4.0.main|ofile = Q20151582015164.L3m_R7_SCI_V4.0_SSS_1deg|prod = SSS|palfile = /sdps/sdpsoper/Science/OCSSW/V2015.2/data/common/palette/sss.pal|processing version = V4.0|meas = 1|stype = 3|datamin = 0.000000|datamax = 70.000000|lonwest = -180.000000|loneast = 180.000000|latsouth = -90.000000|latnorth = 90.000000|resolution = 1deg|projection = RECT|gap_fill = 0|seam_lon = -180.000000|minobs = 0|deflate = 4|oformat = HDF5|precision = F|
    HDF5_GLOBAL.L2_Flag_Names: POINTING,NAV,LANDRED,ICERED,REFL_1STOKESMOONRED,REFL_1STOKESGAL,TFTADIFFRED,RFI_REGION,SAOVERFLOW,COLDWATERRED,WINDRED,TBCONS
    HDF5_GLOBAL.Period_Start_Year: 2015
    HDF5_GLOBAL.Period_Start_Day: 158
    HDF5_GLOBAL.Period_End_Year: 2015
    HDF5_GLOBAL.Period_End_Day: 158
    HDF5_GLOBAL.Start_Time: 2015158013204597
    HDF5_GLOBAL.End_Time: 2015158124519488
    HDF5_GLOBAL.Start_Year: 2015
    HDF5_GLOBAL.Start_Day: 158
    HDF5_GLOBAL.Start_Millisec: 5524596
    HDF5_GLOBAL.End_Year: 2015
    HDF5_GLOBAL.End_Day: 158
    HDF5_GLOBAL.End_Millisec: 45919487
    HDF5_GLOBAL.Start_Orbit: 21446
    HDF5_GLOBAL.End_Orbit: 21452
    HDF5_GLOBAL.Map_Projection: Equidistant Cylindrical
    HDF5_GLOBAL.Latitude_Units: degrees North
    HDF5_GLOBAL.Longitude_Units: degrees East
    HDF5_GLOBAL.Northernmost_Latitude: 90.0
    HDF5_GLOBAL.Southernmost_Latitude: -90.0
    HDF5_GLOBAL.Westernmost_Longitude: -180.0
    HDF5_GLOBAL.Easternmost_Longitude: 180.0
    HDF5_GLOBAL.Latitude_Step: 1.0
    HDF5_GLOBAL.Longitude_Step: 1.0
    HDF5_GLOBAL.SW_Point_Latitude: -89.5
    HDF5_GLOBAL.SW_Point_Longitude: -179.5
    HDF5_GLOBAL.Data_Bins: 5155
    HDF5_GLOBAL.Number_of_Lines: 180
    HDF5_GLOBAL.Number_of_Columns: 360
    HDF5_GLOBAL.Parameter: Sea Surface Salinity
    HDF5_GLOBAL.Measure: Mean
    HDF5_GLOBAL.Units: psu
    HDF5_GLOBAL.Scaling: linear
    HDF5_GLOBAL.Scaling_Equation: (Slope*l3m_data) + Intercept = Parameter value
    HDF5_GLOBAL.Slope: 1.0
    HDF5_GLOBAL.Intercept: 0.0
    HDF5_GLOBAL.Data_Minimum: 25.3962
    HDF5_GLOBAL.Data_Maximum: 38.6452
    HDF5_GLOBAL.Suggested_Image_Scaling_Minimum: 0.0
    HDF5_GLOBAL.Suggested_Image_Scaling_Maximum: 70.0
    HDF5_GLOBAL.Suggested_Image_Scaling_Type: ATAN
    HDF5_GLOBAL.Suggested_Image_Scaling_Applied: No
    HDF5_GLOBAL._lastModified: 2015184121146000
```

When I attempt to covert the product to covjson I get the following 

```
lmcgibbn@LMC-056430 /usr/local/pycovjson(master) $ pycovjson-convert -i ~/Desktop/Q20151582015164.L3m_R7_SCI_V4.0_SSS_1deg.bz2.nc4 -o ~/Desktop/Q20151582015164.L3m_R7_SCI_V4.0_SSS_1deg.bz2.nc4.covjson
Traceback (most recent call last):
  File "/Users/lmcgibbn/miniconda3/bin/pycovjson-convert", line 9, in <module>
    load_entry_point('pycovjson==0.3.8', 'console_scripts', 'pycovjson-convert')()
  File "/Users/lmcgibbn/miniconda3/lib/python3.5/site-packages/pycovjson-0.3.8-py3.5.egg/pycovjson/cli/convert.py", line 66, in main
  File "/Users/lmcgibbn/miniconda3/lib/python3.5/site-packages/pycovjson-0.3.8-py3.5.egg/pycovjson/write.py", line 33, in __init__
  File "/Users/lmcgibbn/miniconda3/lib/python3.5/site-packages/pycovjson-0.3.8-py3.5.egg/pycovjson/read_netcdf.py", line 347, in get_axes
  File "/Users/lmcgibbn/miniconda3/lib/python3.5/site-packages/xarray-0.8.2-py3.5.egg/xarray/core/common.py", line 194, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataArray' object has no attribute 'standard_name'
```

I've not tried to debug this yet however it seems to be a bug. I've seen error messages similar to this before and I am going to start logging each occurrence here from now on so we can even write tests to try and verify if bugs are present.
